---
- hosts: all

  tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ack-grep
        - clang-format-3.6
        - clang-3.6
        - llvm
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - flex
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - composer:
        command: "global require"
        arguments: "squizlabs/php_codesniffer=*"
      become: yes
      tags:
        - all
        - php

    - pip: name={{ item }} state=latest
      become: yes
      with_items:
        - pylint
        - ansible-lint
        - yamllint
        - bashate
      tags:
        - all

    - gem: name={{ item }} state=latest user_install=no
      become: yes
      ignore_errors: yes
      with_items:
        - mdl
        - haml-lint
        - sqlint
        - rubocop
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=yes state=latest
      become: yes
      ignore_errors: yes
      with_items:
        - pug-lint
        - livedown
        - js-yaml
        - stylelint
        - jsonlint
        - eslint
        - eslint-plugin-flowtype
        - eslint-plugin-import
        - eslint-import-resolver-webpack
        - eslint-plugin-jsx-a11y
        - eslint-config-airbnb
        - eslint-plugin-react
      tags:
        - all
        - eslint

    - copy:
        src: ./files/eslintrc
        dest: ~/.eslintrc
        backup: yes
      tags:
        - all
        - eslint
