---
- hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/env python3'

  tasks:
    # - lineinfile:
    #     regexp: ~/.local
    #     path: ~/.bashrc
    #     line: "export PATH=$PATH:~/.local/bin;"

    - homebrew:
        update_homebrew: true
      when: ansible_os_family == 'Darwin'

    - homebrew_tap:
        name: "{{ item }}"
      with_items:
        # - homebrew/dupes
        - homebrew/php
      when: ansible_os_family == 'Darwin'

    - homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - node
        - php71
        - composer

      when: ansible_os_family == 'Darwin'

    # - shell: |
    #     sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    #     echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
    #   when: ansible_distribution == 'Ubuntu'

    - apt: name={{ item }} state=latest
      become: true
      with_items:
        # - mono-runtime
        - ruby
        - ruby-dev
        - php
        - nodejs
        - cmake
        - python-dev
        - openssl
        - libssl-dev
        - ack-grep
        - clang-format-3.6
        - clang-3.6
        - llvm
        - exuberant-ctags
        - curl
        - python3-apt
        - python3-pycurl
        - python3-dev
        - python3-setuptools
        - flex
      when: ansible_os_family == 'Ubuntu'
