---
- hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/env python3'

  tasks:
    - shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - shell: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - mono-runtime
        - ruby
        - ruby-dev
        - php
        - nodejs
        - cmake
        - python-dev
