---
- hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/env python3'

  tasks:
    - shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ruby
        - ruby-dev
        - php
        - nodejs
        - cmake
