---

- hosts: all

  vars:
    myvim: "alias myvim='docker run -it --rm -v /tmp:/tmp:cached -v $HOME/myvim/backups:/root/.vim/backups:cached -v $HOME/myvim/plugged:/root/.vim/plugged:delegated -v `pwd`:/app:delegated -w /app mokevnin/dotfiles nvim'"

  tasks:

    # - lineinfile:
    #     dest: /host/home/.bashrc
    #     line: "{{ myvim }}"
    #     regexp: "myvim"
    #     state: present
    #       # owner=foo
    #     # insertafter=EOF
    #     # create=True

    - lineinfile:
        dest: /host/home/.bash_profile
        line: "{{ myvim }}"
        regexp: "myvim"
        state: present
          # owner=foo
        # insertafter=EOF
        # create=True

    # - lineinfile:
    #     regexp: ~/.local
    #     path: ~/.bash_profile
    #     line: "export PATH=$PATH:~/.local/bin;"

    # - homebrew:
    #     name: "{{ item }}"
    #     state: latest
    #   with_items:
    #     - node
    #     - php71
    #     - composer

      # when: ansible_os_family == 'Darwin'

    # - name: Ensure apt-transport-https is installed.
    #   apt: name=apt-transport-https state=present
    #   when: ansible_os_family == "Debian"

    # - name: Add Nodesource apt key.
    #   apt_key:
    #     url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    #     state: present
    #   become: yes
    #   when: ansible_os_family == "Debian"

    # - name: Add NodeSource repositories for Node.js.
    #   apt_repository:
    #     repo: "{{ item }}"
    #     state: present
    #   with_items:
    #     - "deb https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_distribution_release }} main"
    #     - "deb-src https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_distribution_release }} main"
    #   become: yes
    #   when: ansible_os_family == "Debian"

    # - apt: name={{ item }} state=latest update_cache=yes
    #   become: true
    #   with_items:
    #     # - mono-runtime
    #     - ruby
    #     - ruby-dev
    #     - php
    #     - nodejs
    #     - cmake
    #     - python-dev
    #     - openssl
    #     - libssl-dev
    #     - ack-grep
    #     - silversearcher-ag
    #     - clang-format-3.6
    #     - clang-3.6
    #     - llvm
    #     - exuberant-ctags
    #     - curl
    #     - python3-apt
    #     - python3-pycurl
    #     - python3-dev
    #     - python3-setuptools
    #     - flex
    #   when: ansible_os_family == "Debian"
