---

- hosts: localhost

  vars:
    myvim: "alias myvim='docker run -it --rm -v /tmp:/tmp:cached -v $HOME/myvim/backups:/root/.vim/backups:cached -v $HOME/myvim/plugged:/root/.vim/plugged:delegated -v `pwd`:/app:delegated -w /app mokevnin/dotfiles nvim'"

  tasks:

    # - lineinfile:
    #     dest: /host/home/.bashrc
    #     line: "{{ myvim }}"
    #     regexp: "myvim"
    #     state: present
    #       # owner=foo
    #     # insertafter=EOF
    #     # create=True

    - lineinfile:
        dest: /host/home/.bash_profile
        line: "{{ myvim }}"
        regexp: "myvim"
        state: present
        owner: "{{ lookup('env','HOST_USER') }}"
        create: true
